services:
  app:
    image: asocks-ws
    container_name: asocks-ws
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8011:8011
    volumes:
      - ./.bin/:/root/
      - ./configs/:/root/configs/
    env_file:
      - .env
    networks:
      - asocks-ws
networks:
  asocks-ws:
    external: true